---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.appname }}-clusterrole
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
      - secrets
  - verbs:
      - get
      - list
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appname }}-crbinding  
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appname }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.appname }}-clusterrole