---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.appname }}-clusterrole
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces    
    verbs:
      - get
      - list
  - apiGroups:
      - 'kubeflow.org'
    resources:
      - notebooks
    verbs:
      - get
      - list

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appname }}-crbinding  
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appname }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.appname }}-clusterrole