kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    app: {{ .Values.appname }}
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - {{ .Values.appname }}
        from:
          kind: ImageStreamTag
          name: {{ .Values.appname }}:latest
      type: ImageChange
  strategy:
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appname }}
        deploymentconfig: {{ .Values.appname }}
    spec:
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: {{ .Values.appname }}
            defaultMode: 420
      containers:
        - name: {{ .Values.appname }}
          image: >-
            image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.appname }}:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.appname }}
          volumeMounts:
            - name: webhook-tls-certs
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs

    