# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: {{ .Values.appname }}
#   labels:
#     app: {{ .Values.appname }}
#     app.belongs.to: AdvancedAnalytic
# spec:
#   replicas: {{ .Values.replicacount }}
#   selector:
#     matchLabels:
#       app: {{ .Values.appname }}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: {{ .Values.appname }}
#         deploymentconfig: {{ .Values.appname }}
#     spec:
#       containers:
#         - name: {{ .Values.appname }}
#           image: >-
#             image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.appname }}:latest
#           imagePullPolicy: Always