kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
spec:
  to:
    kind: Service
    name: {{ .Values.appname }}
    weight: 100
  port:
    targetPort: {{ .Values.appname }}-5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None