kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
spec:
  ports:
    - name: {{ .Values.appname }}-8080
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP